### ISSUE TITLE
VPN Cannot Connect Client to Telegram

### ISSUE THREAD

**Issue by kratos47mhs** [bepass-org/warp-plus#189] opened 2024-07-17 13:52 UTC
# Issue Report: VPN Cannot Connect Client to Telegram

**Repository:** [bepass-org/warp-plus](https://github.com/bepass-org/warp-plus)

**Issue Title:** VPN Cannot Connect Client to Telegram

**Description:**

I am experiencing an issue with the warp-plus VPN service where it fails to connect the client to Telegram. Despite successfully establishing a VPN connection, Telegram remains inaccessible. Below are the details of the problem:

**Steps to Reproduce:**
1. Install and set up warp-plus VPN following the instructions provided in the repository.
2. Connect to the VPN.
3. Attempt to access Telegram.

**Expected Behavior:**
Telegram should be accessible once the VPN connection is established.

**Actual Behavior:**
Telegram fails to connect, displaying a network error.

**Additional Information:**
- **VPN Version:**v1.2.3
- **Operating System:** Ubuntu 22.04 LTS
- **Telegram Version:** 5.2.3

**Potential Cause:**
It is possible that the VPN is not routing traffic correctly for Telegram or there may be an issue with the VPN server's ability to handle Telegram's network requirements.

**Request for Assistance:**
Could you please investigate this issue and provide guidance on how to resolve it? Any suggestions or fixes would be greatly appreciated.

Thank you for your attention to this matter. I look forward to your response.

---

If you need any further information or assistance in reproducing this issue, please let me know.

Best regards,

Farokh

**Comment by markpash** [comment] 2024-07-27 00:50
Duplicate of #65

**Closed by markpash** 2024-07-27 00:50 UTC
